const activities = [
    { city: 'telaviv', type: 'mall', name: 'Dizengoff Center Mall', description: '', image: '' },
    { city: 'telaviv', type: 'touristic', name: 'Shuk HaCarmel', description: '', image: '' },
    { city: 'telaviv', type: 'archeology', name: 'Eretz Israel Museum', description: '', image: '' },
    { city: 'telaviv', type: 'trails', name: 'Yarkon Park', description: '', image: '' },
    { city: 'telaviv', type: 'religious', name: 'Great Synagogue of TLV', description: '', image: '' },
    { city: 'telaviv', type: 'mall', name: 'TLV Mall', description: '', image: '' },
    { city: 'telaviv', type: 'touristic', name: 'Florentin', description: '', image: '' },
    { city: 'telaviv', type: 'archeology', name: 'Tel Grisa / Napoleon Hill', description: '', image: '' },
    { city: 'telaviv', type: 'trails', name: 'Pardesim Stream', description: '', image: '' },
    { city: 'telaviv', type: 'religious', name: 'Beit Hafutsot', description: '', image: '' },
    { city: 'telaviv', type: 'mall', name: 'Azraeli Mall', description: '', image: '' },
    { city: 'telaviv', type: 'touristic', name: 'Jaffa', description: '', image: '' },
    { city: 'telaviv', type: 'archeology', name: 'Tell Qasile', description: '', image: '' },
    { city: 'telaviv', type: 'trails', name: 'Park Hamesila', description: '', image: '' },
    { city: 'telaviv', type: 'religious', name: 'Yitshak Rabin Center', description: '', image: '' },
    { city: 'telaviv', type: 'mall', name: 'Ramat Aviv Mall', description: '', image: '' },
    { city: 'telaviv', type: 'touristic', name: 'Tayelet', description: '', image: '' },
    { city: 'telaviv', type: 'archeology', name: 'The Egyptian Gate in Yaffa', description: '', image: '' },
    { city: 'telaviv', type: 'trails', name: 'Charles Clore Park', description: '', image: '' },
    { city: 'telaviv', type: 'religious', name: 'Nahalat Binyamin Synagogue', description: '', image: '' },
    { city: 'telaviv', type: 'mall', name: 'Weizmann City Mall', description: '', image: '' },
    { city: 'telaviv', type: 'touristic', name: 'Neve Tsedek', description: '', image: '' },
    { city: 'telaviv', type: 'archeology', name: 'Sheva Tahanot', description: '', image: '' },
    { city: 'telaviv', type: 'trails', name: 'The Great Synagogue of Ramat Aviv', description: '', image: '' },
    { city: 'telaviv', type: 'mall', name: 'City Garden', description: '', image: '' },
    { city: 'telaviv', type: 'touristic', name: 'Habima Square', description: '', image: '' },
    { city: 'telaviv', type: 'trails', name: 'Mechachem Begin Park', description: '', image: '' },
    { city: 'telaviv', type: 'mall', name: 'Ayalon Mall', description: '', image: '' },
    { city: 'telaviv', type: 'touristic', name: 'Yitshak Rabin Center', description: '', image: '' },
    { city: 'telaviv', type: 'mall', name: 'Dizengoff Center Mall', description: '', image: '' },
    { city: 'telaviv', type: 'touristic', name: 'TLV Museum of Art', description: '', image: '' },
    { city: 'telaviv', type: 'trails', name: 'North Dog Beach - Tel Baruch', description: '', image: '' },
    { city: 'jerusalem', type: 'mall', name: 'Malcha Mall', description: '', image: '' },
    { city: 'jerusalem', type: 'touristic', name: 'Vieille ville', description: '', image: '' },
    { city: 'jerusalem', type: 'archeology', name: 'Cité de David', description: '', image: '' },
    { city: 'jerusalem', type: 'trails', name: 'Jerusalem Trail', description: '', image: '' },
    { city: 'jerusalem', type: 'religious', name: 'Grande synagogue', description: '', image: '' },
    { city: 'jerusalem', type: 'mall', name: 'Hadar Mall', description: '', image: '' },
    { city: 'jerusalem', type: 'touristic', name: 'Promenade de Bak\'a', description: '', image: '' },
    { city: 'jerusalem', type: 'archeology', name: 'Tunnels du Mur', description: '', image: '' },
    { city: 'jerusalem', type: 'trails', name: 'Jerusalem Hills Trail', description: '', image: '' },
    { city: 'jerusalem', type: 'religious', name: 'Kotel', description: '', image: '' },
    { city: 'jerusalem', type: 'mall', name: 'Central Bus Station', description: '', image: '' },
    { city: 'jerusalem', type: 'touristic', name: 'Mamilla', description: '', image: '' },
    { city: 'jerusalem', type: 'archeology', name: 'The Western Wall', description: '', image: '' },
    { city: 'jerusalem', type: 'trails', name: 'Ein Lavan Trail', description: '', image: '' },
    { city: 'jerusalem', type: 'religious', name: 'Mont du Temple', description: '', image: '' },
    { city: 'jerusalem', type: 'mall', name: 'Center One', description: '', image: '' },
    { city: 'jerusalem', type: 'touristic', name: 'Mea Shearim', description: '', image: '' },
    { city: 'jerusalem', type: 'archeology', name: 'The Temple Mount', description: '', image: '' },
    { city: 'jerusalem', type: 'trails', name: 'Sataf Nature Reserve', description: '', image: '' },
    { city: 'jerusalem', type: 'religious', name: 'Hurva Synagogue', description: '', image: '' },
    { city: 'jerusalem', type: 'mall', name: 'Rav Shefa Mall', description: '', image: '' },
    { city: 'jerusalem', type: 'touristic', name: 'Har HaTzofim', description: '', image: '' },
    { city: 'jerusalem', type: 'archeology', name: 'The Tower of David Museum', description: '', image: '' },
    { city: 'jerusalem', type: 'trails', name: 'Jerusalem Forest', description: '', image: '' },
    { city: 'jerusalem', type: 'religious', name: 'Mount of Olives', description: '', image: '' },
    { city: 'jerusalem', type: 'mall', name: 'Ramot Mall', description: '', image: '' },
    { city: 'jerusalem', type: 'touristic', name: 'The Davidson Center', description: '', image: '' },
    { city: 'jerusalem', type: 'archeology', name: 'Emek Hamatzleva', description: '', image: '' },
    { city: 'haifa', type: 'mall', name: 'Cenomi Haifa Mall', description: '', image: '' },
    { city: 'haifa', type: 'touristic', name: 'High Garden', description: '', image: '' },
    { city: 'haifa', type: 'archeology', name: 'Mont Carmel', description: '', image: '' },
    { city: 'haifa', type: 'trails', name: 'Carmel National Park', description: '', image: '' },
    { city: 'haifa', type: 'religious', name: 'The Great Synagogue', description: '', image: '' },
    { city: 'haifa', type: 'mall', name: 'Azraeli Mall Haifa', description: '', image: '' },
    { city: 'haifa', type: 'touristic', name: 'The German Colony', description: '', image: '' },
    { city: 'haifa', type: 'archeology', name: 'Roman Road in Haifa', description: '', image: '' },
    { city: 'haifa', type: 'trails', name: 'Haifa\'s Beach', description: '', image: '' },
    { city: 'haifa', type: 'religious', name: 'Cave of Elija', description: '', image: '' },
    { city: 'haifa', type: 'mall', name: 'Grand Canyon Haifa', description: '', image: '' },
    { city: 'haifa', type: 'touristic', name: 'Haifa Educational Zoo', description: '', image: '' },
    { city: 'haifa', type: 'archeology', name: 'Carmel Mountain', description: '', image: '' },
    { city: 'haifa', type: 'trails', name: 'The Ramchal Synagogue', description: '', image: '' },
    { city: 'haifa', type: 'mall', name: 'Cinema Mall Haifa', description: '', image: '' },
    { city: 'haifa', type: 'touristic', name: 'Haifa Cable Car', description: '', image: '' },
    { city: 'haifa', type: 'archeology', name: 'Louis Promenade', description: '', image: '' },
    { city: 'haifa', type: 'trails', name: 'Nesher Park', description: '', image: '' },
    { city: 'haifa', type: 'mall', name: 'Castra Center', description: '', image: '' },
    { city: 'haifa', type: 'touristic', name: 'The Lighthouse Promenade', description: '', image: '' },
    { city: 'haifa', type: 'mall', name: 'Auditorium Square Mall', description: '', image: '' },
    { city: 'akko', type: 'mall', name: 'Azraeli Akko', description: '', image: '' },
    { city: 'akko', type: 'touristic', name: 'Citadelle', description: '', image: '' },
    { city: 'akko', type: 'archeology', name: 'Crusader Citadel', description: '', image: '' },
    { city: 'akko', type: 'trails', name: 'Akko Promenade', description: '', image: '' },
    { city: 'akko', type: 'religious', name: 'Synagogue Tunisienne d\'Acre', description: '', image: '' },
    { city: 'akko', type: 'mall', name: 'Akko Mall', description: '', image: '' },
    { city: 'akko', type: 'touristic', name: 'Old City of Akko', description: '', image: '' },
    { city: 'akko', type: 'archeology', name: 'Templar Tunnel', description: '', image: '' },
    { city: 'akko', type: 'trails', name: 'Nahal Keziv Nature Reserve', description: '', image: '' },
    { city: 'akko', type: 'religious', name: 'Or Torah Synagogue', description: '', image: '' },
    { city: 'akko', type: 'mall', name: 'Akko Port', description: '', image: '' },
    { city: 'akko', type: 'touristic', name: 'Market Akko Port', description: '', image: '' },
    { city: 'akko', type: 'archeology', name: 'Akkos Old City', description: '', image: '' },
    { city: 'akko', type: 'trails', name: 'Rosh Hanikra Coastal Trail', description: '', image: '' },
    { city: 'akko', type: 'religious', name: 'The Ramchal Synagogue', description: '', image: '' },
    { city: 'akko', type: 'mall', name: 'Nesher Park', description: '', image: '' },
    { city: 'akko', type: 'touristic', name: 'Trails', description: '', image: '' },
    { city: 'akko', type: 'religious', name: 'The Tunisian Synagogue', description: '', image: '' },
    { city: 'akko', type: 'religious', name: 'The Karaite Synagogue', description: '', image: '' },
    { city: 'akko', type: 'religious', name: 'The Ramchal\'s Tomb', description: '', image: '' },
    { city: 'hadera', type: 'mall', name: 'Ofer Lev Hadera', description: '', image: '' },
    { city: 'hadera', type: 'touristic', name: 'Hadera River Park', description: '', image: '' },
    { city: 'hadera', type: 'archeology', name: 'Tel Hadera', description: '', image: '' },
    { city: 'hadera', type: 'trails', name: 'Nahal Hadera Park', description: '', image: '' },
    { city: 'hadera', type: 'religious', name: 'Ohel Yaakov Synagogue', description: '', image: '' },
    { city: 'hadera', type: 'mall', name: 'Mall Hahof Village', description: '', image: '' },
    { city: 'hadera', type: 'touristic', name: 'Hadera Beach', description: '', image: '' },
    { city: 'hadera', type: 'archeology', name: 'Tel Shikmona', description: '', image: '' },
    { city: 'hadera', type: 'religious', name: 'Breslov Synagogue', description: '', image: '' },
    { city: 'hadera', type: 'mall', name: 'Hadera Gates Mall', description: '', image: '' },
    { city: 'hadera', type: 'touristic', name: 'Hadera Stream', description: '', image: '' },
    { city: 'hadera', type: 'archeology', name: 'Archeaological Park', description: '', image: '' },
    { city: 'hadera', type: 'mall', name: 'MIXX Shopping Center', description: '', image: '' },
    { city: 'hadera', type: 'mall', name: 'Mall Hapardes Shopping Mall', description: '', image: '' },
    { city: 'hadera', type: 'mall', name: 'Scenter Park Hadera', description: '', image: '' },
    { city: 'hadera', type: 'mall', name: 'Mitram Kniot Center One', description: '', image: '' },
    { city: 'beersheva', type: 'mall', name: 'Azraeli Negev Mall', description: '', image: '' },
    { city: 'beersheva', type: 'touristic', name: 'Abraham\'s Well International Visitors Center', description: '', image: '' },
    { city: 'beersheva', type: 'archeology', name: 'Tel Beer Sheva National Park', description: '', image: '' },
    { city: 'beersheva', type: 'trails', name: 'Ramon Crater', description: '', image: '' },
    { city: 'beersheva', type: 'religious', name: 'Ohel Yaakov Synagogue', description: '', image: '' },
    { city: 'beersheva', type: 'mall', name: 'Ofer Lev Hadera', description: '', image: '' },
    { city: 'beersheva', type: 'touristic', name: 'Negev Museum of Art', description: '', image: '' },
    { city: 'beersheva', type: 'archeology', name: 'Abraham\'s Well', description: '', image: '' },
    { city: 'beersheva', type: 'trails', name: 'Beer Sheva River Park', description: '', image: '' },
    { city: 'beersheva', type: 'religious', name: 'Yeshivat Hanegev', description: '', image: '' },
    { city: 'beersheva', type: 'mall', name: 'Grand Canyon Beer Sheva', description: '', image: '' },
    { city: 'beersheva', type: 'touristic', name: 'Old City of Beer Sheva', description: '', image: '' },
    { city: 'beersheva', type: 'archeology', name: 'Horvat Uza', description: '', image: '' },
    { city: 'beersheva', type: 'trails', name: 'Big Crater Geological Park', description: '', image: '' },
    { city: 'beersheva', type: 'religious', name: 'Yeshivat Hesder Beer Sheva', description: '', image: '' },
    { city: 'beersheva', type: 'mall', name: 'Hanegev Mall', description: '', image: '' },
    { city: 'beersheva', type: 'touristic', name: 'Joe Alon Center for Beduim Culture', description: '', image: '' },
    { city: 'beersheva', type: 'archeology', name: 'Negev Highlands Trail', description: '', image: '' },
    { city: 'beersheva', type: 'trails', name: 'British Military Cemetery', description: '', image: '' },
    { city: 'beersheva', type: 'religious', name: 'Ben Gourion Park', description: '', image: '' },
    { city: 'ashdod', type: 'mall', name: 'Sea Mall', description: '', image: '' },
    { city: 'ashdod', type: 'touristic', name: 'Ashdod Beach', description: '', image: '' },
    { city: 'ashdod', type: 'archeology', name: 'Tel Ashdod', description: '', image: '' },
    { city: 'ashdod', type: 'trails', name: 'Ashdod Yam Park', description: '', image: '' },
    { city: 'ashdod', type: 'religious', name: 'The Big Synagogue of Ashdod', description: '', image: '' },
    { city: 'ashdod', type: 'mall', name: 'City Mall', description: '', image: '' },
    { city: 'ashdod', type: 'touristic', name: 'Ashdod Art Museum', description: '', image: '' },
    { city: 'ashdod', type: 'archeology', name: 'Ashdod Harbor Excavation', description: '', image: '' },
    { city: 'ashdod', type: 'trails', name: 'Gan Hagat', description: '', image: '' },
    { city: 'ashdod', type: 'religious', name: 'Migdal Ahhod', description: '', image: '' },
    { city: 'ashdod', type: 'mall', name: 'MonArt Arts Center', description: '', image: '' },
    { city: 'ashdod', type: 'touristic', name: 'Tel Es-Safi / Gath', description: '', image: '' },
    { city: 'ashdod', type: 'archeology', name: 'The Eye of the Sun', description: '', image: '' },
    { city: 'ashdod', type: 'trails', name: 'Tel Mor', description: '', image: '' },
    { city: 'ashdod', type: 'religious', name: 'The Lachish Stream Park', description: '', image: '' },
    { city: 'eilat', type: 'mall', name: 'Ice Mall', description: '', image: '' },
    { city: 'eilat', type: 'touristic', name: 'Plage', description: '', image: '' },
    { city: 'eilat', type: 'archeology', name: 'The Ancient City of Eilat', description: '', image: '' },
    { city: 'eilat', type: 'trails', name: 'Timna Park', description: '', image: '' },
    { city: 'eilat', type: 'religious', name: 'Kings City', description: '', image: '' },
    { city: 'eilat', type: 'mall', name: 'Mall Haim', description: '', image: '' },
    { city: 'eilat', type: 'touristic', name: 'Eilat Coral Beach Nature Reserve', description: '', image: '' },
    { city: 'eilat', type: 'archeology', name: 'Eilat Mountains', description: '', image: '' },
    { city: 'eilat', type: 'trails', name: 'Dolphin Reef', description: '', image: '' },
    { city: 'eilat', type: 'religious', name: 'Red Canyon', description: '', image: '' },
    { city: 'eilat', type: 'mall', name: 'Eilat City Center', description: '', image: '' },
    { city: 'eilat', type: 'touristic', name: 'Eilat Underwater Observatory Marine Park', description: '', image: '' },
    { city: 'eilat', type: 'archeology', name: 'Eilat Promenade', description: '', image: '' }
];

export default activities;


function searchActivities() {
    const city = document.getElementById('city').value;
    const activityType = document.getElementById('activity-type').value;
    const resultsContainer = document.getElementById('results');

    resultsContainer.innerHTML = '';

    const filteredActivities = activities.filter(activity => activity.city === city && activity.type === activityType);

    if (filteredActivities.length === 0) {
        resultsContainer.innerHTML = '<p>No activity found.</p>';
    } else {
        filteredActivities.forEach(activity => {
            const resultItem = document.createElement('div');
            resultItem.className = 'result-item';

            const img = document.createElement('img');
            img.src = activity.image;
            img.alt = activity.name;

            const description = document.createElement('div');
            description.innerHTML = `<h3>${activity.name}</h3><p>${activity.description}</p>`;

            resultItem.appendChild(img);
            resultItem.appendChild(description);
            resultsContainer.appendChild(resultItem);
        });
    }
}
